name 'deploy-user'
maintainer 'Barney Hanlon & Walter Dolce'
maintainer_email 'bhanlon@sessiondigital.com, wdolce@sessiondigital.com'
license 'all_rights'
description 'Installs/Configures deploy-user'
long_description 'Installs/Configures deploy-user'
version '0.9.0'

depends 'ssh_known_hosts'
depends 'sudo'
